app = "proyecto-final-progra-iv-2025"
primary_region = "gru" # gru = São Paulo, scl = Santiago de Chile

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python manage.py migrate"

[env]
  # Variables públicas (No secretas). Las secretas van en el panel web.
  PORT = "8080"
  DEBUG = "False"
  ALLOWED_HOSTS = "proyecto-final-progra-iv-2025.fly.dev,tiendaplus.com.ar,www.tiendaplus.com.ar"
  SITE_URL = "https://tiendaplus.com.ar"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
