# Generated by Django 5.2.7 on 2026-05-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_nuevo',
            field=models.CharField(max_length=30),
        ),
    ]
