# Generated by Django 5.2.7 on 2026-05-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_historialpedido_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ciudad_envio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad / Localidad'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_postal_envio',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email_envio',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_envio',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notas_envio',
            field=models.TextField(blank=True, help_text='Ej: Timbre 2B, dejar en portería, etc.', null=True, verbose_name='Notas para el envío'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='provincia_envio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_envio',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono / WhatsApp'),
        ),
    ]
