# Generated by Django 5.2.7 on 2025-11-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_historialpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
