# Generated by Django 5.2.7 on 2026-05-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_pedido_ciudad_envio_pedido_codigo_postal_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_envio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Método de envío'),
        ),
    ]
