# Generated by Django 5.2.7 on 2026-05-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_pedido_costo_envio_pedido_metodo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='depto_envio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Depto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_envio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='piso_envio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle'),
        ),
    ]
