# Generated by Django 5.2.7 on 2026-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_pedido_depto_envio_pedido_numero_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio_gratis_activo', models.BooleanField(default=True, help_text='Si está activo, se muestra la barra de progreso en el carrito.', verbose_name='Promo envío gratis activa')),
                ('envio_gratis_umbral', models.DecimalField(decimal_places=2, default=29000, help_text='El cliente obtiene envío gratis cuando su carrito supera este monto.', max_digits=10, verbose_name='Monto mínimo para envío gratis ($)')),
                ('envio_gratis_mensaje', models.CharField(default='¡Envío GRATIS en compras mayores a ${umbral}!', help_text='Usá {umbral} para insertar el monto. Ej: ¡Envío GRATIS en compras mayores a ${umbral}!', max_length=200, verbose_name='Mensaje de la barra')),
                ('envio_gratis_mensaje_logrado', models.CharField(default='🎉 ¡Desbloqueaste envío GRATIS!', help_text='Lo que ve el cliente cuando alcanza el monto.', max_length=200, verbose_name='Mensaje cuando se alcanza')),
            ],
            options={
                'verbose_name': 'Configuración de la Tienda',
                'verbose_name_plural': 'Configuración de la Tienda',
            },
        ),
    ]
