# Generated by Django 5.2.7 on 2026-07-11 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_codigodescuento_envio_gratis'),
        ('ventas', '0007_add_configuracion_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cupon_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='productos.codigodescuento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='El monto en pesos que se restó del subtotal gracias al cupón.', max_digits=10, verbose_name='Monto descontado'),
        ),
    ]
