# Generated by Django 5.2.7 on 2025-11-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_pedidolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
