# Generated by Django 5.2.7 on 2025-11-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido']},
        ),
    ]
