# Generated by Django 5.2.7 on 2026-06-19 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI / CUIT')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono / WhatsApp')),
                ('calle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=20, null=True, verbose_name='Piso')),
                ('depto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Depto')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad / Localidad')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
                ('pais', models.CharField(blank=True, default='Argentina', max_length=100, null=True, verbose_name='País')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
