# Generated by Django 5.2.7 on 2026-05-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alto_cm',
            field=models.PositiveIntegerField(default=10, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho_cm',
            field=models.PositiveIntegerField(default=15, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo_cm',
            field=models.PositiveIntegerField(default=20, verbose_name='Largo (cm)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_gramos',
            field=models.PositiveIntegerField(default=500, help_text='Peso del producto en gramos. Ej: 500 = medio kilo.', verbose_name='Peso (gramos)'),
        ),
    ]
