# Generated by Django 5.2.7 on 2025-11-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_delete_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
