# Generated by Django 5.2.7 on 2026-05-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_alto_cm_producto_ancho_cm_producto_largo_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, help_text='Activar para mostrar este producto como oferta.', verbose_name='En oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_combo',
            field=models.BooleanField(default=False, help_text='Marcar si este producto es un kit que incluye varios items.', verbose_name='Es Kit/Combo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='etiqueta_oferta',
            field=models.CharField(blank=True, help_text="Texto del badge. Ej: '🏠 COMBO -15%', '🔥 2x1', 'NOVEDAD'", max_length=30, verbose_name='Etiqueta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_fin_oferta',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que expira la oferta. Se usa para el countdown.', null=True, verbose_name='Oferta válida hasta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento. Dejar vacío si no tiene oferta.', max_digits=10, null=True, verbose_name='Precio de oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='productos_incluidos',
            field=models.TextField(blank=True, help_text="Descripción de lo que incluye. Ej: 'Cepillo Deslanador + Rodillo Quitapelusas'", verbose_name='Productos incluidos en el kit'),
        ),
    ]
