# Generated by Django 5.2.7 on 2025-11-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_titulo_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='productos/portadas/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
