# Generated by Django 5.2.7 on 2026-06-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_en_oferta_producto_es_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_carrusel',
            field=models.BooleanField(default=False, help_text='Activar para que el producto aparezca en el slider gigante del Home.', verbose_name='Mostrar en Carrusel'),
        ),
    ]
