# Generated by Django 5.2.7 on 2026-06-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_en_carrusel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portadaproducto',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Portada de producto', 'verbose_name_plural': 'Portadas de producto'},
        ),
        migrations.AddField(
            model_name='portadaproducto',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización (0 es la portada principal).'),
        ),
    ]
