# Generated by Django 5.2.7 on 2025-11-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_options_producto_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
