# Generated by Django 5.2.7 on 2026-06-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_portadaproducto_options_portadaproducto_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='video_tiktok_url',
            field=models.URLField(blank=True, help_text='Pega el enlace del video de TikTok (Ej: https://www.tiktok.com/@usuario/video/1234567)', null=True, verbose_name='Enlace de TikTok'),
        ),
    ]
