# Generated by Django 5.2.7 on 2026-07-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_video_tiktok_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: FELIPE20, INFLUENCER10. Sin espacios, preferí mayúsculas.', max_length=50, unique=True, verbose_name='Código')),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje (%)'), ('monto_fijo', 'Monto Fijo ($)')], default='porcentaje', max_length=20, verbose_name='Tipo de descuento')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Si el tipo es Porcentaje, ingresá 15 para un 15% OFF. Si es Monto Fijo, ingresá la cifra en pesos.', max_digits=10, verbose_name='Valor del descuento')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Válido desde')),
                ('fecha_fin', models.DateTimeField(verbose_name='Válido hasta')),
                ('uso_maximo', models.PositiveIntegerField(default=100, help_text='Cantidad máxima de veces que este código puede ser usado. 0 = sin límite.', verbose_name='Usos máximos')),
                ('usos_actuales', models.PositiveIntegerField(default=0, editable=False, verbose_name='Usos actuales')),
                ('activo', models.BooleanField(default=True, help_text='Apagá el toggle para desactivar el cupón sin borrarlo.', verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Código de Descuento',
                'verbose_name_plural': 'Códigos de Descuento',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CampaniaDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Black Friday, Liquidación de Invierno, Promo Día del Gato', max_length=100, verbose_name='Nombre de la campaña')),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje (%)'), ('monto_fijo', 'Monto Fijo ($)')], default='porcentaje', max_length=20, verbose_name='Tipo de descuento')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Si el tipo es Porcentaje, ingresá 20 para un 20% OFF. Si es Monto Fijo, ingresá la cifra en pesos.', max_digits=10, verbose_name='Valor del descuento')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Inicio de la campaña')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin de la campaña')),
                ('activa', models.BooleanField(default=True, help_text='Debe estar activa Y dentro del rango de fechas para aplicarse.', verbose_name='¿Activa?')),
                ('productos', models.ManyToManyField(blank=True, help_text='Seleccioná los productos a los que aplica esta campaña.', related_name='campanias', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Campaña de Descuento',
                'verbose_name_plural': 'Campañas de Descuento',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
