# Generated by Django 5.2.7 on 2025-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='productos/portadas/'),
        ),
    ]
