# Generated by Django 5.2.7 on 2026-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_add_campania_y_codigo_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigodescuento',
            name='envio_gratis',
            field=models.BooleanField(default=False, help_text='Si marcás esta opción, el cliente no pagará envío, sin importar el monto de su carrito.', verbose_name='¿Incluye Envío Gratis?'),
        ),
    ]
