# Generated by Django 5.2.7 on 2025-11-25 19:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='portada',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='productos/portadas/'),
        ),
    ]
