# Generated by Django 5.2.7 on 2025-12-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_imagenproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
