# Generated by Django 5.2.7 on 2025-12-09 18:23

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_delete_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortadaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='productos/portadas/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portadas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Portada de producto',
                'verbose_name_plural': 'Portadas de producto',
            },
        ),
    ]
